version: "3"
networks:
  api_server_default:
    external: true
services:
  ctf-portal-backend:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_ENTITIES: ${DB_ENTITIES}
      FRONTEND_HOST: ${FRONTEND_HOST}
    ports:
      - 3000:3000
